const config = {
  style: "mapbox://styles/ilabmedia/clwvgiiki065l01nx5b502uso",
  accessToken:
    "pk.eyJ1IjoiaWxhYm1lZGlhIiwiYSI6ImNpbHYycXZ2bTAxajZ1c2tzdWU1b3gydnYifQ.AHxl8pPZsjsqoz95-604nw",
  showMarkers: true,
  inset: false,
  theme: "dark",
  use3dTerrain: false, //set true for enabling 3D maps.
  auto: false,
  chapters: [
    /* ------------------------ start ----------------------- */
    {
      id: "start",
      alignment: "centered",
      hidden: true,
      location: {
        center: [120.96316, 23.75529],
        zoom: 6.7,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 0 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 0},
        {layer: "Port of Taipei", opacity: 0},
        {layer: "Taichung", opacity: 0},
        {layer: "Hualien", opacity: 0},
        {layer: "Mailiao", opacity: 0},
        {layer: "Key-Port-Inner-Dot", opacity: 0},
        {layer: "Key-Port-Outer-Dot", opacity: 0},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 0 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 0},
        {layer: "Port of Taipei", opacity: 0},
        {layer: "Taichung", opacity: 0},
        {layer: "Hualien", opacity: 0},
        {layer: "Mailiao", opacity: 0},
        {layer: "Key-Port-Inner-Dot", opacity: 0},
        {layer: "Key-Port-Outer-Dot", opacity: 0},
      ],
    },
    /* ---------------------- chapter 1 --------------------- */
    {
      id: "chapter1",
      alignment: "right",
      hidden: false,
      description:
        "<p>Chinese authorities do not announce a specific location for the inspections, but they intend to target the Port of Kaohsiung, Taiwan’s busiest port.</p>",
      location: {
        center: [120.96316, 23.75529],
        zoom: 6.7,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 0 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },        
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 0},
        {layer: "Port of Taipei", opacity: 0},
        {layer: "Taichung", opacity: 0},
        {layer: "Hualien", opacity: 0},
        {layer: "Mailiao", opacity: 0},
        {layer: "Key-Port-Inner-Dot", opacity: 0},
        {layer: "Key-Port-Outer-Dot", opacity: 0},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 0 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 0},
        {layer: "Port of Taipei", opacity: 0},
        {layer: "Taichung", opacity: 0},
        {layer: "Hualien", opacity: 0},
        {layer: "Mailiao", opacity: 0},
        {layer: "Key-Port-Inner-Dot", opacity: 0},
        {layer: "Key-Port-Outer-Dot", opacity: 0},
      ],
    },
    /* ---------------------- chapter 2 --------------------- */
    {
      id: "chapter2",
      alignment: "right",
      hidden: false,
      description: `<p class="text">In 2022, an estimated <span id="info-icon" class="info-icon"><a
      class="info-icon-link"
      href="https://portwatch.imf.org/pages/data-and-methodology"
      target="_blank"
      rel="noopener"
      >57 percent</a
    >
    <span id="tooltip-text" class="tooltip-text"
      >Based on author’s calculations of <a id="data" href="https://portwatch.imf.org/pages/data-and-methodology" target="_blank"
      rel="noopener">data</a> provided by IMF-PortWatch as of April 3, 2024. Percent values are based on trade value not volume.</span
    >
  </span> of Taiwan’s maritime trade entered through the Port of Kaohsiung, making it an indispensable commercial hub for the island.
</p>
`,
      location: {
        center: [122.49747, 23.72517],
        zoom: 7,
        pitch: 0,
        bearing: 0,
        speed: 0.1,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0.7, duration: 750 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 0 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 1, duration: 750 },
        { layer: "symbols", opacity: 0, duration: 750 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 0 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
    /* ---------------------- chapter 3 --------------------- */
    {
      id: "chapter3",
      alignment: "right",
      hidden: false,
      description:
        "<p>China positions more than 10 law enforcement patrol vessels off the coast of Kaohsiung. About 48 hours after the initial announcement, Chinese authorities issue notices that enforcement is beginning and that its patrol ships will stop noncompliant vessels.</p><p style='font-size: 14px; display: flex; align-items: center;'><span class='coast-guard-circle'>&#x25CF;</span> Law enforcement vessels</p>",
      location: {
        center: [120.66977, 22.39901],
        zoom: 8.39,
        pitch: 0,
        bearing: 0,
        speed: 0.1,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 1, duration: 750 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 0 },
        {
          layer: "taiwan-contiguous-zone-outline",
          opacity: 0,
        },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 0 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
    /* ---------------------- chapter 4 --------------------- */
    {
      id: "chapter4",
      alignment: "right",
      hidden: false,
      description:
        `<p>The vessels intrude into Taiwan’s 24-nautical-mile contiguous zone and occasionally approach the 12-nautical-mile territorial seas boundary.</p><p>This is symbolically important since China does not recognize Taiwan’s claims to these boundaries. During large-scale military exercises around Taiwan in April 2023, PLA vessels <a href="https://chinapower.csis.org/analyzing-chinas-response-to-taiwan-president-tsai-ing-wen-transit/" target="_blank">intruded</a> into Taiwan’s contiguous zone in a maneuver intended to delegitimize Taiwan’s claims. </p>`,
      location: {
        center: [120.63455, 22.13205],
        zoom: 8.39,
        pitch: 0,
        bearing: 0,
        speed: 0.1,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55, duration: 750 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1, duration: 750 },
        {
          layer: "taiwan-contiguous-zone-outline",
          opacity: 0.55,
          duration: 750,
        },
        { layer: "taiwan-sea-labels", opacity: 1, duration: 750 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 1, duration: 750 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0, duration: 750 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
    /* --------------------- chapter 4.5 -------------------- */
    {
      id: "chapter45",
      alignment: "right",
      hidden: false,
      description:
        "<p>China also deploys a smaller contingent of law enforcement vessels within the Taiwan Strait off the coast of other major ports at Taichung and Taipei.</p>",
      location: {
        center: [121.08549, 24.69907],
        zoom: 8.1,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 1, duration: 750 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
    /* ---------------------- chapter 5 --------------------- */
    {
      id: "chapter5",
      alignment: "right",
      hidden: false,
      description:
        "<p>Supporting these law enforcement vessels are several maritime militia fishing vessels extending along Taiwan’s contiguous zone. They are not authorized to board or inspect commercial vessels. Instead, they fill in gaps in ISR and complicate Taiwan’s maritime domain awareness by swarming in certain areas.</p><p style='font-size: 14px; display: flex; align-items: center;'><span class='maritime-circle'>&#x25CF;</span>Maritime militia vessels</p>",
      location: {
        center: [121.08549, 24.69907],
        zoom: 8.1,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 1 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 0, duration: 750 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0, duration: 750 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 1, duration: 750 },
        { layer: "coast_guard_glow", opacity: 1, duration: 750 },
        { layer: "maritime_militia_dot", opacity: 1, duration: 750 },
        { layer: "maritime_militia_glow", opacity: 1, duration: 750 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
    /* ---------------------- chapter 6 --------------------- */
    {
      id: "chapter6",
      alignment: "right",
      hidden: false,
      description: `<p>In total, about 20 maritime militia vessels are positioned around the island’s contiguous zone. China could deploy significantly more militia forces, but they are not as well trained as the coast guard, and Beijing may worry about their discipline and ability to face off against Taiwan’s coast guard.</p>`,
      location: {
        center: [121.69805, 23.70374],
        zoom: 6.72,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 1, duration: 750 },
        { layer: "coast_guard_glow", opacity: 1, duration: 750 },
        { layer: "maritime_militia_dot", opacity: 1, duration: 750 },
        { layer: "maritime_militia_glow", opacity: 1, duration: 750 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 1 },
        { layer: "coast_guard_glow", opacity: 1 },
        { layer: "maritime_militia_dot", opacity: 1 },
        { layer: "maritime_militia_glow", opacity: 1 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
    /* ---------------------- chapter 7 --------------------- */
    {
      id: "chapter7",
      alignment: "right",
      hidden: false,
      description: `<p>While this quarantine is ostensibly a law enforcement operation, the military plays a key supporting role.</p>
      <p>China’s navy deploys five surface action groups (SAGs) to encircle Taiwan from a distance. This amounts to nearly 30 warships—an unprecedentedly large deployment around Taiwan.</p><p style='font-size: 14px; display: flex; align-items: center;'><span class='pla-circle'>&#x25CF;</span>PLA Navy</p>`,
      location: {
        center: [122.93549, 23.70166],
        zoom: 6.08,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "PLA_ship1", opacity: 0 },
        { layer: "PLA_ship2", opacity: 0 },
        { layer: "PLA_ship3", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 1 },
        { layer: "coast_guard_glow", opacity: 1 },
        { layer: "maritime_militia_dot", opacity: 1 },
        { layer: "maritime_militia_glow", opacity: 1 },
        { layer: "PLA_dots", opacity: 1, duration: 750 },
        { layer: "PLA_glow", opacity: 1, duration: 750 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "PLA_ship1", opacity: 0 },
        { layer: "PLA_ship2", opacity: 0 },
        { layer: "PLA_ship3", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0, duration: 750 },
        { layer: "coast_guard_glow", opacity: 0, duration: 750 },
        { layer: "maritime_militia_dot", opacity: 0, duration: 750 },
        { layer: "maritime_militia_glow", opacity: 0, duration: 750 },
        { layer: "PLA_dots", opacity: 0, duration: 750 },
        { layer: "PLA_glow", opacity: 0, duration: 750 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
    /* --------------------- chapter 7.5 -------------------- */
    {
      id: "chapter75",
      alignment: "right",
      hidden: false,
      description: `<p>Each SAG comprises three to six ships, including destroyers, frigates, support vessels, and covertly deployed attack submarines. They are meant to intimidate Taiwan, deter intervention by foreign forces, and extend China’s air and maritime domain awareness farther into the Pacific.</p>`,
      location: {
        center: [122.863953, 21.979608],
        zoom: 8.1,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 1, duration: 750 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 1, duration: 750 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "PLA_ship1", opacity: 1, duration: 750 },
        { layer: "PLA_ship2", opacity: 1, duration: 750 },
        { layer: "PLA_ship3", opacity: 1, duration: 750 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 0, duration: 750 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "PLA_ship1", opacity: 0, duration: 750 },
        { layer: "PLA_ship2", opacity: 0, duration: 750 },
        { layer: "PLA_ship3", opacity: 0, duration: 750 },
        { layer: "coast_guard_dot", opacity: 0, duration: 750 },
        { layer: "coast_guard_glow", opacity: 0, duration: 750 },
        { layer: "maritime_militia_dot", opacity: 0, duration: 750 },
        { layer: "maritime_militia_glow", opacity: 0, duration: 750 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
    /* ---------------------- chapter 8 --------------------- */
    {
      id: "chapter8",
      alignment: "right",
      hidden: false,
      description: `<p>As the operations take place, the PLA constantly flies sorties of manned and unmanned aircraft around Taiwan to monitor traffic.</p><p><span style='font-size: 14px; display: flex; align-items: center;'><img src='assets/drone.svg' alt='icon' style='width:30px;height:30px; margin-right: 20px;'/>PLA aircraft</span></p>`,
      location: {
        center: [123.14643, 23.62152],
        zoom: 5.97,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 1, duration: 750 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "PLA_ship1", opacity: 0 },
        { layer: "PLA_ship2", opacity: 0 },
        { layer: "PLA_ship3", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 1, duration: 750 },
        { layer: "coast_guard_glow", opacity: 1, duration: 750 },
        { layer: "maritime_militia_dot", opacity: 1, duration: 750 },
        { layer: "maritime_militia_glow", opacity: 1, duration: 750 },
        { layer: "PLA_dots", opacity: 1, duration: 750 },
        { layer: "PLA_glow", opacity: 1, duration: 750 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0, duration: 750 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "PLA_ship1", opacity: 0 },
        { layer: "PLA_ship2", opacity: 0 },
        { layer: "PLA_ship3", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0, duration: 750 },
        { layer: "coast_guard_glow", opacity: 0, duration: 750 },
        { layer: "maritime_militia_dot", opacity: 0, duration: 750 },
        { layer: "maritime_militia_glow", opacity: 0, duration: 750 },
        { layer: "PLA_dots", opacity: 0, duration: 750 },
        { layer: "PLA_glow", opacity: 0, duration: 750 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
    /* --------------------- chapter 9 --------------------- */
    {
      id: "chapter9",
      alignment: "right",
      hidden: false,
      description: `<p>Over the course of one week, Chinese law enforcement vessels only stop and search one or two vessels in total and focus solely on Taiwan-owned vessels.</p>
      <p>Beijing does not need universal compliance with the customs rules in order to claim success. Compliance by around 75 percent of shipping companies would be a considerable success for China.</p>`,
      location: {
        center: [121.69805, 23.70374],
        zoom: 6.72,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
    /* --------------------- chapter 10 --------------------- */
    {
      id: "chapter10",
      alignment: "centered",
      hidden: false,
      description: `<p>Chinese-flagged shipping vessels—which account for a significant share of the total traffic—universally comply with Chinese authorities, and Beijing permits them to enter Taiwan’s ports.</p>

      <p>Beijing counts on most foreign shipping companies complying with the “enhanced customs rules” to avoid reprisals, but several companies headquartered in Taiwan, the United States, and certain other countries publicly oppose and disregard the rules.</p>`,
      location: {
        center: [121.69805, 23.70374],
        zoom: 6.72,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
      onChapterExit: [
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "symbols", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "taiwan-territorial-sea", opacity: 0.55 },
        { layer: "taiwan-contiguous-zone-fill", opacity: 1 },
        { layer: "taiwan-contiguous-zone-outline", opacity: 0.55 },
        { layer: "taiwan-sea-labels", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        /*labels*/
        {layer: "Kaohsiung", opacity: 1},
        {layer: "Kaohsiung-Inner-Dot copy", opacity: 1},
        {layer: "Kaohsiung-Outer-Dot copy", opacity: 1},
        {layer: "Keelung", opacity: 1},
        {layer: "Port of Taipei", opacity: 1},
        {layer: "Taichung", opacity: 1},
        {layer: "Hualien", opacity: 1},
        {layer: "Mailiao", opacity: 1},
        {layer: "Key-Port-Inner-Dot", opacity: 1},
        {layer: "Key-Port-Outer-Dot", opacity: 1},
      ],
    },
  ],
}

export default config
