const config = {
  // scenario 2
  style: "mapbox://styles/ilabmedia/clwz2cfhk00f101nm9wnz16s6",
  accessToken:
    "pk.eyJ1IjoiaWxhYm1lZGlhIiwiYSI6ImNpbHYycXZ2bTAxajZ1c2tzdWU1b3gydnYifQ.AHxl8pPZsjsqoz95-604nw",
  showMarkers: true,
  inset: false,
  theme: "dark",
  use3dTerrain: false, //set true for enabling 3D maps.
  auto: false,
  chapters: [
    /* ------------------------ start ----------------------- */
    {
      id: "start",
      alignment: "right",
      hidden: true,
      location: {
        center: [121.60665, 23.74937],
        zoom: 6.7,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
    },
    /* ---------------------- chapter 1 --------------------- */
    {
      id: "chapter1",
      alignment: "right",
      hidden: false,
      description:
        `<p>This time, however, China publicly announces a quarantine area covering the entire island of Taiwan.</p><p>The zone extends 24 nautical miles from Taiwan’s territorial baseline, matching with Taiwan’s claimed contiguous zone. This is intended to delegitimize Taiwan’s claimed contiguous zone and demonstrate China’s willingness and capability to impose its will in an area ostensibly under Taipei’s jurisdiction.</p>`,
      location: {
        center: [121.60665, 23.74937],
        zoom: 6.7,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 1 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 1 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
    },
    /* ---------------------- chapter 2 --------------------- */
    {
      id: "chapter2",
      alignment: "right",
      hidden: false,
      description:
        `<p>Chinese authorities announce that the inspection regime will go into effect 48 hours after declaration. China will require the shipper of any cargo destined for Taiwan to file advance notice with Chinese customs and law enforcement officials.</p>`,
      location: {
        center: [121.60665, 23.74937],
        zoom: 6.7,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0, duration: 750 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 1 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 1, duration: 750 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
    },
    /* ---------------------- chapter 3 --------------------- */
    {
      id: "chapter3",
      alignment: "right",
      hidden: false,
      description: `<p>China again deploys law enforcement vessels to lead the quarantine. The greatest concentration, consisting of more than 10 coast guard and maritime safety vessels, is positioned off the coast of Kaohsiung.</p>`,
      location: {
        center: [120.43517, 22.46602],
        zoom: 8.4,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
    },
    /* --------------------- chapter 3.5 -------------------- */
    {
      id: "chapter35",
      alignment: "right",
      hidden: false,
      description: `<p>However, in this scenario, China sends a much larger overall contingent of law enforcement patrol ships to encircle the island.</p><p>It deploys a dozen of these off the west coast ports of Taipei and Taichung. It also sends nine near the northern Port of Keelung—Taiwan’s second-busiest import hub—and six to the smaller eastern ports of Hualien and Su\’ao.</p>`,
      location: {
        center: [122.08018, 24.70145],
        zoom: 7.59,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0, duration: 750 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 1, duration: 750 },
        { layer: "coast_guard_glow", opacity: 1, duration: 750 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
    },
    /* ---------------------- chapter 4 --------------------- */
    {
      id: "chapter4",
      alignment: "right",
      hidden: false,
      description: `<p>This deployment of more than three dozen law enforcement vessels amounts to an unprecedentedly large maritime operation for China. It would constitute approximately one-fourth of China’s oceangoing CCG and MSA fleet.</p>`,
      location: {
        center: [120.96316, 23.75529],
        zoom: 6.7,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 1 },
        { layer: "coast_guard_dot", opacity: 1 },
        { layer: "coast_guard_glow", opacity: 1 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 1, duration: 750 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 1, duration: 750 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 1 },
        { layer: "coast_guard_dot", opacity: 0, duration: 750 },
        { layer: "coast_guard_glow", opacity: 0, duration: 750 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
    },
    /* ---------------------- chapter 5 --------------------- */
    {
      id: "chapter5",
      alignment: "right",
      hidden: false,
      description: `<p>Roughly 40 maritime militia vessels also swarm along the contiguous zone to fill in gaps between law enforcement vessels.</p><p>As in the limited quarantine scenario, the maritime militia does not participate in boarding and inspecting vessels. It focuses on conducting ISR for China and complicating Taiwan’s maritime domain awareness.</p>`,
      location: {
        center: [119.8286, 23.48061],
        zoom: 8.1,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 1 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 1 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0 },
        { layer: "carrier_ship_2", opacity: 0 },
        { layer: "carrier_ship_3", opacity: 0 },
        { layer: "carrier_ship_4", opacity: 0 },
        { layer: "carrier_ship_5", opacity: 0 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0, duration: 750 },
        { layer: "drones", opacity: 1, duration: 750 },
        { layer: "maritime_militia", opacity: 0, duration: 750 },
        { layer: "PLA", opacity: 1 },
        // { layer: "taiwan-quarantine-outline", opacity: 1 },
        { layer: "coast_guard_dot", opacity: 1, duration: 750 },
        { layer: "coast_guard_glow", opacity: 1, duration: 750 },
        { layer: "maritime_militia_dot", opacity: 1, duration: 750 },
        { layer: "maritime_militia_glow", opacity: 1, duration: 750 },
        { layer: "PLA_dots", opacity: 1, duration: 750 },
        { layer: "PLA_glow", opacity: 1, duration: 750 },
        { layer: "carrier_dot", opacity: 1, duration: 750 },
        { layer: "carrier_glow", opacity: 1, duration: 750 },
        { layer: "carrier_ship_1", opacity: 0, duration: 750 },
        { layer: "carrier_ship_2", opacity: 0, duration: 750 },
        { layer: "carrier_ship_3", opacity: 0, duration: 750 },
        { layer: "carrier_ship_4", opacity: 0, duration: 750 },
        { layer: "carrier_ship_5", opacity: 0, duration: 750 },
      ],
    },
    /* ---------------------- chapter 6 ---------s------------ */
    {
      id: "chapter6",
      alignment: "right",
      hidden: false,
      description: `<p>As in the limited quarantine scenario, China’s navy deploys five SAGs to extend China’s ISR, intimidate Taiwan, and deter U.S. and other forces that may try to intervene. PLA aircraft also fly regular sorties to conduct ISR around Taiwan.</p>`,
      location: {
        center: [123.66626, 23.64968],
        zoom: 5.89,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "drones", opacity: 1 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 1 },
        { layer: "coast_guard_dot", opacity: 1 },
        { layer: "coast_guard_glow", opacity: 1 },
        { layer: "maritime_militia_dot", opacity: 1 },
        { layer: "maritime_militia_glow", opacity: 1 },
        { layer: "PLA_dots", opacity: 1 },
        { layer: "PLA_glow", opacity: 1 },
        { layer: "carrier_dot", opacity: 1 },
        { layer: "carrier_glow", opacity: 1 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 1, duration: 750 },
        { layer: "drones", opacity: 0, duration: 750 },
        { layer: "maritime_militia", opacity: 1, duration: 750 },
        { layer: "PLA", opacity: 1, duration: 750 },
        // { layer: "taiwan-quarantine-outline", opacity: 1 },
        { layer: "coast_guard_dot", opacity: 0, duration: 750 },
        { layer: "coast_guard_glow", opacity: 0, duration: 750 },
        { layer: "maritime_militia_dot", opacity: 0, duration: 750 },
        { layer: "maritime_militia_glow", opacity: 0, duration: 750 },
        { layer: "PLA_dots", opacity: 0, duration: 750 },
        { layer: "PLA_glow", opacity: 0, duration: 750 },
        { layer: "carrier_dot", opacity: 0, duration: 750 },
        { layer: "carrier_glow", opacity: 0, duration: 750 },
        { layer: "carrier_ship_1", opacity: 1, duration: 750 },
        { layer: "carrier_ship_2", opacity: 1, duration: 750 },
        { layer: "carrier_ship_3", opacity: 1, duration: 750 },
        { layer: "carrier_ship_4", opacity: 1, duration: 750 },
        { layer: "carrier_ship_5", opacity: 1, duration: 750 },
      ],
    },
    /* ---------------------- chapter 7 --------------------- */
    {
      id: "chapter7",
      alignment: "right",
      hidden: false,
      description: `<p>This time, China supplements its naval deployment by positioning the <i>Shandong</i> aircraft carrier and its strike group southeast of Taiwan. It launches frequent sorties of J-15 fighters east of Taiwan, repeating operations that the PLA <a href="https://www.csis.org/analysis/analyzing-chinas-escalation-after-taiwan-president-tsais-transit-through-united-states" target="_blank">exercised</a> in recent years.</p><p style='font-size: 14px; display: flex; align-items: center;'><span class='aircraft-carrier-circle'>&#x25CF;</span><span style="font-style: italic; margin-right: 5px;">Shandong</span> aircraft carrier group</p>`,
      location: {
        center: [123.236247, 20.664492],
        zoom: 8.1,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 1 },
        { layer: "china_coast_guard", opacity: 1 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 1 },
        { layer: "PLA", opacity: 1 },
        // { layer: "taiwan-quarantine-outline", opacity: 1 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 1 },
        { layer: "carrier_ship_2", opacity: 1 },
        { layer: "carrier_ship_3", opacity: 1 },
        { layer: "carrier_ship_4", opacity: 1 },
        { layer: "carrier_ship_5", opacity: 1 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0, duration: 750 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0, duration: 750 },
        { layer: "PLA", opacity: 0, duration: 750 },
        // { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
        { layer: "carrier_dot", opacity: 0 },
        { layer: "carrier_glow", opacity: 0 },
        { layer: "carrier_ship_1", opacity: 0, duration: 750 },
        { layer: "carrier_ship_2", opacity: 0, duration: 750 },
        { layer: "carrier_ship_3", opacity: 0, duration: 750 },
        { layer: "carrier_ship_4", opacity: 0, duration: 750 },
        { layer: "carrier_ship_5", opacity: 0, duration: 750 },
      ],
    },
    /* ---------------------- chapter 8 --------------------- */
    {
      id: "chapter8",
      alignment: "right",
      hidden: false,
      description: `<p>In this scenario, China is much more active in terms of boarding and searching vessels. Chinese forces stop at least one or two vessels per day for the period of the quarantine, focusing mostly on Taiwan-flagged ships.</p>
      <p>There also appear to be inspections of vessels belonging to the <a href="https://en.mofa.gov.tw/AlliesIndex.aspx?n=1294&sms=1007" target="_blank">dozen countries</a> that still maintain official diplomatic relations with Taiwan. Chinese forces seize noncompliant ships and impound them at nearby ports within China.</p>`,
      location: {
        center: [120.96316, 23.75529],
        zoom: 6.7,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
      ],
    },
    /* ---------------------- chapter 9 --------------------- */
    {
      id: "chapter9",
      alignment: "centered",
      hidden: false,
      description: `<p>Commercial vessels that have filed the appropriate paperwork and had their requests approved are allowed into Taiwan. However, due to heightened uncertainty about the nature of China’s enforcement, many shipping companies choose to delay their shipments, causing a significant and noticeable decline of merchandise trade into Taiwan.</p>`,
      location: {
        center: [120.96316, 23.75529],
        zoom: 6.7,
        pitch: 0,
        bearing: 0,
        speed: 0.2,
      },
      onChapterEnter: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
      ],
      onChapterExit: [
        // { layer: "carrier-strike-group", opacity: 0 },
        { layer: "china_coast_guard", opacity: 0 },
        { layer: "drones", opacity: 0 },
        { layer: "maritime_militia", opacity: 0 },
        { layer: "PLA", opacity: 0 },
        // { layer: "taiwan-quarantine-outline", opacity: 0 },
        { layer: "coast_guard_dot", opacity: 0 },
        { layer: "coast_guard_glow", opacity: 0 },
        { layer: "maritime_militia_dot", opacity: 0 },
        { layer: "maritime_militia_glow", opacity: 0 },
        { layer: "PLA_dots", opacity: 0 },
        { layer: "PLA_glow", opacity: 0 },
      ],
    },
  ],
}

export default config
